openapi: 3.0.0
info:
  title: Tajfi Wallet API
  version: 1.0.0
  description: API for managing Taproot assets using the Tajfi wallet.

servers:
  - url: http://localhost:18881/api/v1
    description: Local development server
  - url: https://api.tajfi.com/api/v1
    description: Demo signet server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Transfer:
      type: object
      properties:
        txid:
          type: string
          description: Transaction ID of the asset transfer.
        timestamp:
          type: string
          description: Timestamp of the asset transfer.
        height:
          type: integer
          description: Anchor transaction height.
        asset_id:
          type: string
          description: Asset ID of the transfer.
        type:
          type: string
          description: Type of the transfer (send/receive).
        amount:
          type: integer
          format: uint64
          description: Amount of the asset transferred.

paths:
  /wallet/connect:
    post:
      summary: Connect a wallet
      description: Authenticate a wallet using a public key and signature.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                public_key:
                  type: string
                  description: 32-byte X-coordinate of the public key
                signature:
                  type: string
                  description: Signature for authentication
              required:
                - public_key
                - signature
      responses:
        '200':
          description: Successful connection
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT token for authorization
        '401':
          description: Unauthorized

  /orders:
    get:
      summary: Retrieve all buy orders
      description: Returns a list of all items listed for sale.
      responses:
        '200':
          description: A list of items for sale.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    asset_id:
                      type: string
                      description: The ID of the asset.
                    amount_to_sell:
                      type: integer
                      description: The amount of the asset to sell.
                    amount_sats_to_receive:
                      type: integer
                      description: The amount of sats to pay for the asset.
                    outpoint:
                      type: object
                      properties:
                        txid:
                          type: string
                          description: The transaction ID of the outpoint.
                        output_index:
                          type: integer
                          description: The output index of the outpoint.
                      required:
                        - txid
                        - output_index
                    virtual_psbt:
                      type: string
                      description: The virtual PSBT associated with the order.
                    anchor_psbt:
                      type: string
                      description: The anchor PSBT associated with the order.
                    passive_asset_psbts:
                      type: array
                      items:
                        type: string
                      description: A list of passive asset PSBTs.
        '500':
          description: Internal Server Error

  /wallet/balances:
    get:
      summary: Get wallet asset balances
      security:
        - bearerAuth: []
      description: Retrieve the current asset balances for all assets in the wallet.
      responses:
        '200':
          description: Successful response with asset balances
          content:
            application/json:
              schema:
                type: object
                properties:
                  asset_balances:
                    type: object
                    additionalProperties:
                      type: object
                      properties:
                        asset_genesis:
                          type: object
                          description: Details about the genesis of the asset.
                          properties:
                            genesis_point:
                              type: string
                              description: The outpoint where the asset was first created, in the form `{txid}:{vout}`.
                            name:
                              type: string
                              description: The name of the asset.
                            meta_hash:
                              type: string
                              description: A hash of any additional metadata linked to the asset.
                            asset_id:
                              type: string
                              description: The unique identifier of the asset.
                            asset_type:
                              type: string
                              enum: [NORMAL, COLLECTIBLE]
                              description: The type of asset (either a normal asset or a collectible).
                            output_index:
                              type: integer
                              description: The index of the output in the genesis transaction.
                        balance:
                          type: string
                          description: The current total balance of the asset in the wallet, including unconfirmed amounts.
                        unconfirmed_balance:
                          type: string
                          description: The current balance of the asset in the wallet that is unavailable for spending until confirmation.
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /wallet/transfers:
    get:
      summary: Retrieve asset transfer history
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of asset transfers
          content:
            application/json:
              schema:
                type: object
                properties:
                  transfers:
                    type: array
                    items:
                      $ref: '#/components/schemas/Transfer'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error


  /wallet/send/decode:
    post:
      summary: Decode a Taproot Asset address
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                  description: The Taproot Asset address to decode.
              required:
                - address
      responses:
        '200':
          description: Decoded Taproot Asset information
          content:
            application/json:
              schema:
                type: object
                properties:
                  encoded:
                    type: string
                    description: The bech32 encoded Taproot Asset address.
                  asset_id:
                    type: string
                    description: The asset ID that uniquely identifies the asset.
                  asset_type:
                    type: string
                    description: The type of the asset.
                  amount:
                    type: string
                    description: The total amount of the asset stored in this Taproot Asset UTXO.
                  group_key:
                    type: string
                    description: The group key of the asset (if it exists).
                  script_key:
                    type: string
                    description: The specific script key the asset must commit to for ownership transfer.
                  internal_key:
                    type: string
                    description: The internal key used for the on-chain output.
                  tapscript_sibling:
                    type: string
                    description: Optional serialized tapscript sibling preimage for additional Taproot paths.
                  taproot_output_key:
                    type: string
                    description: The tweaked internal key that represents the on-chain output key.
                  proof_courier_addr:
                    type: string
                    description: The address of the proof courier service used in proof transfer.
                  asset_version:
                    type: string
                    description: The asset version of the address.
                  address_version:
                    type: string
                    description: The version of the address.
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /wallet/send/start:
    post:
      summary: Start sending an asset
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                invoice:
                  type: string
                  description: Invoice to send assets to
              required:
                - invoice
      responses:
        '200':
          description: Funded PSBT returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  sighash_hex_to_sign:
                    type: string
                    description: The sighash hex to provide a schnorr signature over
                  funded_psbt:
                    type: string
                    description: The funded PSBT hex
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /wallet/send/complete:
    post:
      summary: Complete sending an asset
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                signature_hex:
                  type: string
                  description: The signature hex to derived from the sighash of the /start step.
                psbt:
                  type: string
                  description: The same unsigned PSBT hex from /start step.
              required:
                - psbt
      responses:
        '200':
          description: Asset transfer completed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transfer'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /wallet/receive:
    post:
      summary: Generate an invoice to receive an asset
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                asset_id:
                  type: string
                  description: ID of the asset
                amt:
                  type: integer
                  description: Amount to receive
              required:
                - asset_id
                - amt
      responses:
        '200':
          description: Invoice generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  invoice:
                    type: string
                    description: Invoice to receive assets
        '401':
          description: Unauthorized

  /wallet/sell/start:
    post:
      summary: Initiate the sell process
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                asset_id:
                  type: string
                  description: The ID of the asset to sell.
                amount_to_sell:
                  type: integer
                  format: int64
                  description: Amount of the asset to sell.
              required:
                - asset_id
                - amount_to_sell
      responses:
        '200':
          description: Sell process initiated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  funded_psbt:
                    type: string
                    description: The funded PSBT hex.
                  change_output_index:
                    type: integer
                    description: Index of the change output in the PSBT.
                  passive_asset_psbts:
                    type: array
                    items:
                      type: string
                    description: Passive asset PSBTs.
                  sighash_hex_to_sign:
                    type: string
                    description: The sighash hex to provide a Schnorr signature over.
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /wallet/sell/complete:
    post:
      summary: Finalize the sell process
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                psbt:
                  type: string
                  description: The unsigned PSBT for the sell process.
                sighash_hex:
                  type: string
                  description: The sighash hex generated during the start process.
                signature_hex:
                  type: string
                  description: The Schnorr signature hex over the sighash.
                amount_sats_to_receive:
                  type: integer
                  format: int64
                  description: Amount in satoshis to receive for the asset.
                receive_btc_address:
                  type: string
                  description: The BTC address to receive the payment.
              required:
                - psbt
                - sighash_hex
                - signature_hex
                - amount_sats_to_receive
                - receive_btc_address
      responses:
        '200':
          description: Sell process completed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  signed_virtual_psbt:
                    type: string
                    description: Signed virtual PSBT.
                  modified_anchor_psbt:
                    type: string
                    description: Modified anchor PSBT.
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /wallet/buy/start:
    post:
      summary: Initiate the buy process
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                psbt:
                  type: string
                  description: The PSBT for the buy process.
                anchor_psbt:
                  type: string
                  description: The anchor PSBT for the buy process.
              required:
                - psbt
                - anchor_psbt
      responses:
        '200':
          description: Updated and funded PSBT returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  updated_virtual_psbt:
                    type: string
                    description: The funded PSBT hex.
                  updated_anchor_psbt:
                    type: integer
                    description: The updated anchor PSBT that still requires BTC funding.
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /wallet/buy/complete:
    post:
      summary: Finalize the buy process
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                psbt:
                  type: string
                  description: The PSBT for the buy process.
                anchor_psbt:
                  type: string
                  description: The anchor PSBT for the transaction.
                sighash_hex:
                  type: string
                  description: The sighash hex generated during the start process.
                signature_hex:
                  type: string
                  description: The Schnorr signature hex over the sighash.
                amount_sats_to_pay:
                  type: integer
                  format: int64
                  description: Amount in satoshis to pay for the asset.
              required:
                - psbt
                - anchor_psbt
                - sighash_hex
                - signature_hex
                - amount_sats_to_pay
      responses:
        '200':
          description: Buy process completed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  signed_virtual_psbt:
                    type: string
                    description: Signed virtual PSBT.
                  modified_anchor_psbt:
                    type: string
                    description: Modified anchor PSBT.
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error