openapi: 3.0.0
info:
  title: Tajfi Wallet API
  version: 1.0.0
  description: API for managing Taproot assets using the Tajfi wallet.

servers:
  - url: http://localhost:18881/api/v1
    description: Local development server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Transfer:
      type: object
      properties:
        transfer_timestamp:
          type: string
          description: Timestamp of the asset transfer.
        anchor_tx_hash:
          type: string
          description: Hash of the anchor transaction.
        anchor_tx_height_hint:
          type: integer
          description: Anchor transaction height hint.
        anchor_tx_chain_fees:
          type: string
          description: Fees for the anchor transaction.
        inputs:
          type: array
          items:
            $ref: '#/components/schemas/TransferInput'
          description: Inputs used in the transfer.
        outputs:
          type: array
          items:
            $ref: '#/components/schemas/TransferOutput'
          description: Outputs from the transfer.

    TransferInput:
      type: object
      properties:
        anchor_point:
          type: string
          description: The old/current location of the Taproot Asset commitment spent as input.
        asset_id:
          type: string
          description: The ID of the asset spent.
        script_key:
          type: string
          description: The script key of the asset spent.
        amount:
          type: string
          description: The amount of the asset spent.

    TransferOutput:
      type: object
      properties:
        anchor:
          $ref: '#/components/schemas/Anchor'
          description: The anchor details of the transfer output.
        script_key:
          type: string
          description: Script key of the output.
        script_key_is_local:
          type: boolean
          description: Indicates if the script key is local.
        amount:
          type: string
          description: The amount in the output.
        new_proof_blob:
          type: string
          description: Proof blob for the new asset.
        split_commit_root_hash:
          type: string
          description: Hash of the split commit root.
        output_type:
          type: string
          description: The type of the output.
        asset_version:
          type: string
          description: Version of the asset.
        lock_time:
          type: string
          description: Lock time for the output.
        relative_lock_time:
          type: string
          description: Relative lock time for the output.
        proof_delivery_status:
          type: string
          description: Status of the proof delivery (optional).

    Anchor:
      type: object
      properties:
        outpoint:
          type: string
          description: The outpoint of the anchor.
        value:
          type: string
          description: Value associated with the anchor.
        internal_key:
          type: string
          description: Internal key for the anchor.
        taproot_asset_root:
          type: string
          description: Taproot asset root hash.
        merkle_root:
          type: string
          description: Merkle root associated with the anchor.
        tapscript_sibling:
          type: string
          description: Tapscript sibling (optional).
        num_passive_assets:
          type: integer
          description: Number of passive assets.

paths:
  /wallet/connect:
    post:
      summary: Connect a wallet
      description: Authenticate a wallet using a public key and signature.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                public_key:
                  type: string
                  description: 32-byte X-coordinate of the public key
                signature:
                  type: string
                  description: Signature for authentication
              required:
                - public_key
                - signature
      responses:
        '200':
          description: Successful connection
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT token for authorization
        '401':
          description: Unauthorized

  /wallet/balances:
    get:
      summary: Get wallet asset balances
      security:
        - bearerAuth: []
      description: Retrieve the current asset balances for all assets in the wallet.
      responses:
        '200':
          description: Successful response with asset balances
          content:
            application/json:
              schema:
                type: object
                properties:
                  asset_balances:
                    type: object
                    additionalProperties:
                      type: object
                      properties:
                        asset_genesis:
                          type: object
                          description: Details about the genesis of the asset.
                          properties:
                            genesis_point:
                              type: string
                              description: The outpoint where the asset was first created, in the form `{txid}:{vout}`.
                            name:
                              type: string
                              description: The name of the asset.
                            meta_hash:
                              type: string
                              description: A hash of any additional metadata linked to the asset.
                            asset_id:
                              type: string
                              description: The unique identifier of the asset.
                            asset_type:
                              type: string
                              enum: [NORMAL, COLLECTIBLE]
                              description: The type of asset (either a normal asset or a collectible).
                            output_index:
                              type: integer
                              description: The index of the output in the genesis transaction.
                        balance:
                          type: string
                          description: The current balance of the asset in the wallet.
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /wallet/transfers:
    get:
      summary: Retrieve asset transfer history
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of asset transfers
          content:
            application/json:
              schema:
                type: object
                properties:
                  transfers:
                    type: array
                    items:
                      $ref: '#/components/schemas/Transfer'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error


  /wallet/send/decode:
    post:
      summary: Decode a Taproot Asset address
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                  description: The Taproot Asset address to decode.
              required:
                - address
      responses:
        '200':
          description: Decoded Taproot Asset information
          content:
            application/json:
              schema:
                type: object
                properties:
                  encoded:
                    type: string
                    description: The bech32 encoded Taproot Asset address.
                  asset_id:
                    type: string
                    description: The asset ID that uniquely identifies the asset.
                  asset_type:
                    type: string
                    description: The type of the asset.
                  amount:
                    type: string
                    description: The total amount of the asset stored in this Taproot Asset UTXO.
                  group_key:
                    type: string
                    description: The group key of the asset (if it exists).
                  script_key:
                    type: string
                    description: The specific script key the asset must commit to for ownership transfer.
                  internal_key:
                    type: string
                    description: The internal key used for the on-chain output.
                  tapscript_sibling:
                    type: string
                    description: Optional serialized tapscript sibling preimage for additional Taproot paths.
                  taproot_output_key:
                    type: string
                    description: The tweaked internal key that represents the on-chain output key.
                  proof_courier_addr:
                    type: string
                    description: The address of the proof courier service used in proof transfer.
                  asset_version:
                    type: string
                    description: The asset version of the address.
                  address_version:
                    type: string
                    description: The version of the address.
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /wallet/send/start:
    post:
      summary: Start sending an asset
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                invoice:
                  type: string
                  description: Invoice to send assets to
              required:
                - invoice
      responses:
        '200':
          description: Funded PSBT returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  sighash_hex_to_sign:
                    type: string
                    description: The sighash hex to provide a schnorr signature over
                  funded_psbt:
                    type: string
                    description: The funded PSBT hex
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /wallet/send/complete:
    post:
      summary: Complete sending an asset
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                signature_hex:
                  type: string
                  description: The signature hex to derived from the sighash of the /start step.
                psbt:
                  type: string
                  description: The same unsigned PSBT hex from /start step.
              required:
                - psbt
      responses:
        '200':
          description: Asset transfer completed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transfer'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /wallet/receive:
    post:
      summary: Generate an invoice to receive an asset
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                asset_id:
                  type: string
                  description: ID of the asset
                amt:
                  type: integer
                  description: Amount to receive
              required:
                - asset_id
                - amt
      responses:
        '200':
          description: Invoice generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  invoice:
                    type: string
                    description: Invoice to receive assets
        '401':
          description: Unauthorized